In [1]:
import pandas as pd #importação da biblioteca#

In [6]:
url1 = '/content/olist_customers_dataset.csv' #pegando os arquivos#
url2 = '/content/olist_geolocation_dataset.csv'
url3 = '/content/olist_order_items_dataset.csv'
url4 = '/content/olist_order_payments_dataset.csv'
url5 = '/content/olist_order_reviews_dataset.csv'
url6 = '/content/olist_orders_dataset.csv'
url7 = '/content/olist_products_dataset.csv'
url8 = '/content/olist_sellers_dataset.csv'

In [7]:
customers = pd.read_csv(url1) #lendo todas as bases necessárias#
geolocation = pd.read_csv(url2)
order_items = pd.read_csv(url3)
order_payments = pd.read_csv(url4)
order_reviews = pd.read_csv(url5)
orders = pd.read_csv(url6)
products = pd.read_csv(url7)
sellers = pd.read_csv(url8)

In [8]:
customers.head(5) #lendo a primeira tabela#

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
print('Valores nulos:') #verificando os valores nulos#
display(customers.isnull().sum())

Null values per column in customers DataFrame:

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [10]:
print('\nTipo de dados:') #verificando o tipo dos dados para melhor analise#
display(customers.dtypes)

Data types of each column in customers DataFrame:

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [11]:
geolocation.head() #apresentando a tabela#

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [12]:
display(geolocation.isnull().sum()) #verificando os nulos#

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [14]:
display(geolocation.dtypes) #verificando os tipos#

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [19]:
order_items.head() #apresentando a tabela#

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [17]:
display(order_items.isnull().sum()) #valores nulos#

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [18]:
display(order_items.dtypes) #verificando os tipos#

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [20]:
order_payments.head() #apresentando a tabela#

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [21]:
display(order_payments.isnull().sum()) #verificando os valores nulos#

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [22]:
display(order_payments.dtypes) #verificando os tipos#

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [23]:
order_reviews.head() #apresentando a tabela#

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [24]:
display(order_reviews.isnull().sum()) #verificando os valores nulos, nesse caso são colunas sem muita importância para nossas análises sem necessidade de tratamento#

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [26]:
display(order_reviews.dtypes) #verificando tipos#

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [27]:
orders.head() #apresentando a tabela#

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [28]:
display(orders.isnull().sum())  #verificando valores nulos#

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [29]:
orders_not_delivered = orders[orders['order_status'] != 'delivered'] #puxando apenas os diferentes de entregue#
print('Orders with status other than \'delivered\':')
display(orders_not_delivered.head())

Orders with status other than 'delivered':

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00

In [30]:
orders_not_delivered.shape #verificando o numero de linhas e colunas#

(2963, 8)

In [32]:
orders_delivered = orders[orders['order_status'] == 'delivered']
print('Orders with status \'delivered\':')
display(orders_delivered.head())  #filtrando apenas os entregues#

Orders with status 'delivered':

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [33]:
display(orders_delivered.isnull().sum()) #quando é puxado apenas o entregue os nulos caem muito, sem necessidade de maior análise, dentro do powerbi será criado um flag de pedido concluido/cancelado/em processamento.#

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
order_estimated_delivery_date     0
dtype: int64

In [34]:
display(orders.dtypes) #tipo de pedidos#

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [74]:
print('Unique values in order_status column of orders DataFrame:')
display(orders['order_status'].unique())  #verificando como é preenchido a coluna de status para desenvolver a flag#

Unique values in order_status column of orders DataFrame:

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [35]:
products.head() #apresentando a tabela#

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [36]:
display(products.isnull().sum()) #muitos dados nulos onde temos a categoria, a coluna principal da tabela#

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [37]:
display(products.dtypes) #verificando os tipos#

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [38]:
products.shape #verificando linhas e colunas#

(32951, 9)

In [41]:
products_null_category = products[products['product_category_name'].isnull()]
print('Products with null category name:')
display(products_null_category.head(5)) #filtrando apenas os nulos para encontrar o padrão, o nulo é inconsistente não faz sentido manter na tabela#

Products with null category name:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [42]:
sellers.head() #apresentando a tabela#

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [43]:
display(sellers.isnull().sum()) #verificando nulos#

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [44]:
display(sellers.dtypes) #verificando tipos#

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [72]:
print('Duplicate columns in customers DataFrame:') #verificando se temos colunas repetidas nas tabelas#
display(customers.columns[customers.columns.duplicated()])

print('\nDuplicate columns in geolocation DataFrame:')
display(geolocation.columns[geolocation.columns.duplicated()])

print('\nDuplicate columns in order_items DataFrame:')
display(order_items.columns[order_items.columns.duplicated()])

print('\nDuplicate columns in order_payments DataFrame:')
display(order_payments.columns[order_payments.columns.duplicated()])

print('\nDuplicate columns in order_reviews DataFrame:')
display(order_reviews.columns[order_reviews.columns.duplicated()])

print('\nDuplicate columns in orders DataFrame:')
display(orders.columns[orders.columns.duplicated()])

print('\nDuplicate columns in products DataFrame:')
display(products.columns[products.columns.duplicated()])

print('\nDuplicate columns in sellers DataFrame:')
display(sellers[sellers.duplicated()])

Duplicate columns in customers DataFrame:

Index([], dtype='object')

Duplicate columns in geolocation DataFrame:

Index([], dtype='object')

Duplicate columns in order_items DataFrame:

Index([], dtype='object')

Duplicate columns in order_payments DataFrame:

Index([], dtype='object')

Duplicate columns in order_reviews DataFrame:

Index([], dtype='object')

Duplicate columns in orders DataFrame:

Index([], dtype='object')

Duplicate columns in products DataFrame:

Index([], dtype='object')

Duplicate columns in sellers DataFrame:

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [49]:
customers[customers.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [73]:
geolocation[geolocation.duplicated(keep=False)] #nota-se muitas linhas repetidas com o mesmo id, porem latitude e longitude diferentes, não usaremos isso na analise por isso será removido as linhas duplicadas#

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [55]:
order_items[order_items.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [54]:
order_payments[order_payments.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [52]:
products[products.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [51]:
orders[orders.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [50]:
sellers[sellers.duplicated(keep=False)] #verificando linhas duplicatas na tabela, caso nao apresente nenhuma linha, não existe repetido#

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [58]:
geolocation.shape #verificando linhas e colunas#

(1000163, 5)

In [59]:
geolocation_only_duplicate = geolocation[geolocation.duplicated(keep='first')] #pegando apenas as linhas e colunas duplicadas#
print('Duplicate rows in geolocation DataFrame:')
display(geolocation_only_duplicate)

Duplicate rows in geolocation DataFrame:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [67]:
geolocation.drop_duplicates(inplace=True) #estou dropando as duplicadas#
print('Shape of geolocation DataFrame after removing duplicates:')
display(geolocation.shape)

Shape of geolocation DataFrame after removing duplicates:

(738332, 5)

In [62]:
geolocation[geolocation.duplicated(keep=False)] #verificando se funcionou#

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [68]:
geolocation.to_csv('geolocation_no_duplicates.csv', index=False) #salvando nova base#
print('Geolocation data without duplicates saved to geolocation_no_duplicates.csv')

Geolocation data without duplicates saved to geolocation_no_duplicates.csv

In [69]:
products = products.dropna(subset=['product_category_name']) #tirando os valores nulos de produto#
print('Shape of products DataFrame after removing rows with null product_category_name:')
display(products.shape)

Shape of products DataFrame after removing rows with null product_category_name:

(32341, 9)

In [70]:
display(products.isnull().sum()) #vendo se deu certo#

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

In [71]:
products.to_csv('products_tratados.csv', index=False) #salvando a base#

In [ ]:
#O que foi feito: verificamos os nulos e os tipos, internamente foi definido que as datas e a flag se o pedido foi concluido serão
#desenvolvidas no powerbi, porém limpamos a base de produtos sem categoria e removemos as duplicadas da geolocalização#
#além de servir como base do que ser feito com os pedidos na criação da flag e indicar que as datas estão como object#